name: Publish GitHub Pages

on:
  workflow_dispatch:

jobs:
  build_and_publish_doc_site:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - { binary-version: "2.12", java-version: "temurin@8" }

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.scala.java-version }}
      
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.cache/coursier
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ matrix.scala.binary-version }}-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-${{ matrix.scala.binary-version }}-

      - name: Build and publish website
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
        run: |
          sbt spekka-docs/paradox
          sbt spekka-docs/publishToGitHubPages
